defaults:
  - dataset: capitals  # Placeholder for dataset file
  - _self_  # Ensures the current file is merged after loading the dataset file

model_family: llama2-7b
model_path: null
loss_type: GA_GD
unlearn_epochs: 2
seed: 42
learning_rate: 1e-5
batch_size: 4
forget_loss_lambda: 0.5
forget_loss_lambda_question: 0.0
retain_loss_lambda: 1.0
optimizer : AdamW
npo_beta: 0.1
simnpo_gamma: 0.0
mask_retain_question: False
